language: cpp

os:
  - osx
  - linux

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env: PLATFORM=osx
    - os: linux
      env: PLATFORM=linux
      dist: xenial
      compiler: gcc

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    - develop

install: true
script:
  - 'if [ "$TRAVIS_BRANCH" == "develop" ]; then ./mk $PLATFORM --develop; else ./mk $PLATFORM; fi'
