language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env: PLATFORM=osx
    - os: linux
      env: PLATFORM=linux COMPILER=g++-7
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    - develop

install: true
script:
  - ./.travis/runall.sh
