language: cpp

os: osx

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env: PLATFORM=osx

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

install: true
script:
  - ./mk $PLATFORM
